CREATE DATABASE HRM;

USE HRM;

CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Email NVARCHAR(200) UNIQUE NOT NULL
);

SELECT * FROM Users;

INSERT INTO Users (Name, Email) VALUES ('John Doe', 'johndoe@gmail.com');

CREATE TABLE Orders (
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id)
);

ALTER TABLE Orders
DROP CONSTRAINT FK__Orders__UserId__164452B1;

ALTER TABLE Orders DROP COLUMN UserId;

ALTER TABLE Orders
ADD UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id);

SELECT * FROM Orders;

INSERT INTO Orders (UserId) VALUES (1);

INSERT INTO Orders (UserId) VALUES (1);